jobs:
  bobby:
    branches:
      only:
        - master
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: |
          bundle install
          bundle exec rake db:schema:load
          bundle exec rspec spec
          bundle exec cucumber
  sally:
    branches:
      only:
        - master
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: |
          bundle install
          bundle exec rake db:schema:load
          bundle exec rspec spec
          bundle exec cucumber
          echo "Double trouble"
  workflows: 
    version: 2
    bobby_sally:
      jobs: 
        - bobby
        - sally
